// Data file generated by scripts/gen_data.py — do not edit manually
// Original club data (titles, rates, watch dates) preserved from movie_base table.
export const SEED_MOVIES = [
 {
  "id": 55,
  "title": "Фантазм 2",
  "titleEn": "Phantasm II",
  "year": 1988,
  "country": "США",
  "director": "Дон Коскареллі",
  "genre": "Жахи, Фантастика",
  "season": "2025",
  "date": "2025-08-30",
  "imdb": "https://www.imdb.com/title/tt0098173/",
  "wiki": "https://en.wikipedia.org/wiki/Phantasm_II",
  "poster": "",
  "rates": {
   "dima": 7,
   "deni": 7,
   "yura": 9,
   "ihor": 7
  }
 },
 {
  "id": 54,
  "title": "Повернення живих мерців 2",
  "titleEn": "Return of the Living Dead Part II",
  "year": 1988,
  "country": "США",
  "director": "Кен Відерхорн",
  "genre": "Жахи, Комедія",
  "season": "2025",
  "date": "2025-08-29",
  "imdb": "https://www.imdb.com/title/tt0096430/",
  "wiki": "https://en.wikipedia.org/wiki/Return_of_the_Living_Dead_Part_II",
  "poster": "",
  "rates": {
   "dima": 6,
   "deni": 6,
   "yura": 6,
   "ihor": 6
  }
 },
 {
  "id": 53,
  "title": "Ніч демонів 3",
  "titleEn": "Night of the Demons 3",
  "year": 1997,
  "country": "Канада",
  "director": "Джим Кауфман",
  "genre": "Жахи",
  "season": "2025",
  "date": "2025-08-29",
  "imdb": "https://www.imdb.com/title/tt0120664/",
  "wiki": "https://en.wikipedia.org/wiki/Night_of_the_Demons_3",
  "poster": "",
  "rates": {
   "dima": 7,
   "deni": 8,
   "yura": 8,
   "ihor": 7
  }
 },
 {
  "id": 52,
  "title": "Дюна (2021)",
  "titleEn": "Dune",
  "year": 2021,
  "country": "США, Канада",
  "director": "Дені Вільнев",
  "genre": "Фантастика, Пригоди",
  "season": "2021",
  "date": "2021-09-19",
  "imdb": "https://www.imdb.com/title/tt15239678/",
  "wiki": "https://en.wikipedia.org/wiki/Dune_(2021_film)",
  "poster": "",
  "rates": {
   "dima": 8,
   "deni": 8,
   "yura": 9,
   "ihor": 10
  }
 },
 {
  "id": 51,
  "title": "Сканнери",
  "titleEn": "Scanners",
  "year": 1981,
  "country": "Канада",
  "director": "Девід Кроненберг",
  "genre": "Жахи, Фантастика",
  "season": "2021",
  "date": "2021-08-08",
  "imdb": "https://www.imdb.com/title/tt0084055/",
  "wiki": "https://en.wikipedia.org/wiki/Scanners",
  "poster": "",
  "rates": {
   "dima": 7,
   "deni": 7,
   "yura": 6,
   "ihor": 6
  }
 },
 {
  "id": 50,
  "title": "Срібна куля",
  "titleEn": "Silver Bullet",
  "year": 1985,
  "country": "США",
  "director": "Деніел Еттіас",
  "genre": "Жахи, Детектив",
  "season": "2021",
  "date": "2021-04-17",
  "imdb": "https://www.imdb.com/title/tt0090022/",
  "wiki": "https://en.wikipedia.org/wiki/Silver_Bullet_(film)",
  "poster": "",
  "rates": {
   "dima": 7,
   "deni": 7,
   "yura": 7,
   "ihor": 0
  }
 },
 {
  "id": 49,
  "title": "Франкеншльондра",
  "titleEn": "Frankenhooker",
  "year": 1990,
  "country": "США",
  "director": "Френк Хененлоттер",
  "genre": "Жахи, Комедія",
  "season": "2021",
  "date": "2021-04-10",
  "imdb": "https://www.imdb.com/title/tt0099619/",
  "wiki": "https://en.wikipedia.org/wiki/Frankenhooker",
  "poster": "",
  "rates": {
   "dima": 7,
   "deni": 7,
   "yura": 6,
   "ihor": 7
  }
 },
 {
  "id": 48,
  "title": "Суспільство",
  "titleEn": "Society",
  "year": 1989,
  "country": "США",
  "director": "Браян Юзна",
  "genre": "Жахи, Комедія",
  "season": "2021",
  "date": "2021-04-10",
  "imdb": "https://www.imdb.com/title/tt0098354/",
  "wiki": "https://en.wikipedia.org/wiki/Society_(film)",
  "poster": "",
  "rates": {
   "dima": 4,
   "deni": 4,
   "yura": 4,
   "ihor": 0
  }
 },
 {
  "id": 47,
  "title": "Виконавець бажань 2",
  "titleEn": "Wishmaster 2: Evil Never Dies",
  "year": 1999,
  "country": "США",
  "director": "Джек Шолдер",
  "genre": "Жахи",
  "season": "2021",
  "date": "2021-04-10",
  "imdb": "https://www.imdb.com/title/tt0160498/",
  "wiki": "https://en.wikipedia.org/wiki/Wishmaster_2:_Evil_Never_Dies",
  "poster": "",
  "rates": {
   "dima": 6,
   "deni": 6,
   "yura": 6,
   "ihor": 0
  }
 },
 {
  "id": 46,
  "title": "Виконавець бажань",
  "titleEn": "Wishmaster",
  "year": 1997,
  "country": "США",
  "director": "Роберт Курцман",
  "genre": "Жахи",
  "season": "2021",
  "date": "2021-04-10",
  "imdb": "https://www.imdb.com/title/tt0118591/",
  "wiki": "https://en.wikipedia.org/wiki/Wishmaster",
  "poster": "",
  "rates": {
   "dima": 6,
   "deni": 7,
   "yura": 8,
   "ihor": 0
  }
 },
 {
  "id": 45,
  "title": "Маніяк-поліцейський",
  "titleEn": "Maniac Cop",
  "year": 1988,
  "country": "США",
  "director": "Вільям Люстіг",
  "genre": "Жахи, Трилер",
  "season": "2021",
  "date": "2021-03-07",
  "imdb": "https://www.imdb.com/title/tt0095583/",
  "wiki": "https://en.wikipedia.org/wiki/Maniac_Cop",
  "poster": "",
  "rates": {
   "dima": 6,
   "deni": 6,
   "yura": 4,
   "ihor": 5
  }
 },
 {
  "id": 44,
  "title": "Хронос",
  "titleEn": "Cronos",
  "year": 1993,
  "country": "Мексика",
  "director": "Ґільєрмо дель Торо",
  "genre": "Жахи",
  "season": "2021",
  "date": "2021-03-07",
  "imdb": "https://www.imdb.com/title/tt0104029/",
  "wiki": "https://en.wikipedia.org/wiki/Cronos_(film)",
  "poster": "",
  "rates": {
   "dima": 4,
   "deni": 5,
   "yura": 5,
   "ihor": 2
  }
 },
 {
  "id": 43,
  "title": "Графиня Дракула",
  "titleEn": "Countess Dracula",
  "year": 1971,
  "country": "Велика Британія",
  "director": "Пітер Сассді",
  "genre": "Жахи",
  "season": "2021",
  "date": "2021-01-23",
  "imdb": "https://www.imdb.com/title/tt0066881/",
  "wiki": "https://en.wikipedia.org/wiki/Countess_Dracula",
  "poster": "",
  "rates": {
   "dima": 5,
   "deni": 6,
   "yura": 6,
   "ihor": 0
  }
 },
 {
  "id": 42,
  "title": "Троль (1986)",
  "titleEn": "Troll",
  "year": 1986,
  "country": "США, Італія",
  "director": "Джон Карл Бюхлер",
  "genre": "Жахи, Фентезі",
  "season": "2021",
  "date": "2021-01-23",
  "imdb": "https://www.imdb.com/title/tt0092115/",
  "wiki": "https://en.wikipedia.org/wiki/Troll_(film)",
  "poster": "",
  "rates": {
   "dima": 5,
   "deni": 5,
   "yura": 4,
   "ihor": 6
  }
 },
 {
  "id": 41,
  "title": "Жахаючий",
  "titleEn": "Terrifier",
  "year": 2016,
  "country": "США",
  "director": "Демієн Леоне",
  "genre": "Жахи, Слешер",
  "season": "2020",
  "date": "2020-12-05",
  "imdb": "https://www.imdb.com/title/tt4287324/",
  "wiki": "https://en.wikipedia.org/wiki/Terrifier",
  "poster": "",
  "rates": {
   "dima": 3,
   "deni": 5,
   "yura": 4,
   "ihor": 1
  }
 },
 {
  "id": 40,
  "title": "Ніч демонів 2",
  "titleEn": "Night of the Demons 2",
  "year": 1994,
  "country": "США",
  "director": "Браян Тренчард-Сміт",
  "genre": "Жахи, Комедія",
  "season": "2020",
  "date": "2020-12-05",
  "imdb": "https://www.imdb.com/title/tt0110666/",
  "wiki": "https://en.wikipedia.org/wiki/Night_of_the_Demons_2",
  "poster": "",
  "rates": {
   "dima": 8,
   "deni": 8,
   "yura": 10,
   "ihor": 6
  }
 },
 {
  "id": 39,
  "title": "Судоми",
  "titleEn": "Shivers",
  "year": 1975,
  "country": "Канада",
  "director": "Девід Кроненберг",
  "genre": "Жахи, Фантастика",
  "season": "2020",
  "date": "2020-11-21",
  "imdb": "https://www.imdb.com/title/tt0073705/",
  "wiki": "https://en.wikipedia.org/wiki/Shivers_(film)",
  "poster": "",
  "rates": {
   "dima": 4,
   "deni": 6,
   "yura": 3,
   "ihor": 0
  }
 },
 {
  "id": 38,
  "title": "Наречена реаніматора",
  "titleEn": "Bride of Re-Animator",
  "year": 1990,
  "country": "США",
  "director": "Браян Юзна",
  "genre": "Жахи, Фантастика",
  "season": "2020",
  "date": "2020-11-21",
  "imdb": "https://www.imdb.com/title/tt0101382/",
  "wiki": "https://en.wikipedia.org/wiki/Bride_of_Re-Animator",
  "poster": "",
  "rates": {
   "dima": 3,
   "deni": 3,
   "yura": 3,
   "ihor": 0
  }
 },
 {
  "id": 37,
  "title": "Сновида",
  "titleEn": "Sleepwalkers",
  "year": 1992,
  "country": "США",
  "director": "Мік Гарріс",
  "genre": "Жахи",
  "season": "2020",
  "date": "2020-11-15",
  "imdb": "https://www.imdb.com/title/tt0105433/",
  "wiki": "https://en.wikipedia.org/wiki/Sleepwalkers_(film)",
  "poster": "",
  "rates": {
   "dima": 7,
   "deni": 7,
   "yura": 7,
   "ihor": 0
  }
 },
 {
  "id": 36,
  "title": "Ніч демонів",
  "titleEn": "Night of the Demons",
  "year": 1988,
  "country": "США",
  "director": "Кевін Тенні",
  "genre": "Жахи",
  "season": "2020",
  "date": "2020-11-14",
  "imdb": "https://www.imdb.com/title/tt0095488/",
  "wiki": "https://en.wikipedia.org/wiki/Night_of_the_Demons_(1988_film)",
  "poster": "",
  "rates": {
   "dima": 7,
   "deni": 7,
   "yura": 7,
   "ihor": 0
  }
 },
 {
  "id": 35,
  "title": "Попутник",
  "titleEn": "The Hitcher",
  "year": 1986,
  "country": "США",
  "director": "Роберт Гармон",
  "genre": "Трилер, Жахи",
  "season": "2020",
  "date": "2020-09-05",
  "imdb": "https://www.imdb.com/title/tt0091209/",
  "wiki": "https://en.wikipedia.org/wiki/The_Hitcher",
  "poster": "",
  "rates": {
   "dima": 6,
   "deni": 7,
   "yura": 10,
   "ihor": 5
  }
 },
 {
  "id": 34,
  "title": "ЗЛО",
  "titleEn": "V/H/S",
  "year": 2012,
  "country": "США",
  "director": "Адам Вінґард та ін.",
  "genre": "Жахи",
  "season": "2020",
  "date": "2020-08-23",
  "imdb": "https://www.imdb.com/title/tt1618442/",
  "wiki": "https://en.wikipedia.org/wiki/V/H/S",
  "poster": "",
  "rates": {
   "dima": 5,
   "deni": 5,
   "yura": 6,
   "ihor": 0
  }
 },
 {
  "id": 33,
  "title": "Американський перевертень у Лондоні",
  "titleEn": "An American Werewolf in London",
  "year": 1981,
  "country": "США, Велика Британія",
  "director": "Джон Лендіс",
  "genre": "Жахи, Комедія",
  "season": "2020",
  "date": "2020-08-23",
  "imdb": "https://www.imdb.com/title/tt0082010/",
  "wiki": "https://en.wikipedia.org/wiki/An_American_Werewolf_in_London",
  "poster": "",
  "rates": {
   "dima": 7,
   "deni": 7,
   "yura": 6,
   "ihor": 0
  }
 },
 {
  "id": 32,
  "title": "Крістіна",
  "titleEn": "Christine",
  "year": 1983,
  "country": "США",
  "director": "Джон Карпентер",
  "genre": "Жахи",
  "season": "2020",
  "date": "2020-08-23",
  "imdb": "https://www.imdb.com/title/tt0085333/",
  "wiki": "https://en.wikipedia.org/wiki/Christine_(1983_film)",
  "poster": "",
  "rates": {
   "dima": 5,
   "deni": 5,
   "yura": 5,
   "ihor": 0
  }
 },
 {
  "id": 31,
  "title": "Апостол",
  "titleEn": "Apostle",
  "year": 2018,
  "country": "Велика Британія",
  "director": "Ґарет Еванс",
  "genre": "Жахи",
  "season": "2020",
  "date": "2020-07-18",
  "imdb": "https://www.imdb.com/title/tt6858476/",
  "wiki": "https://en.wikipedia.org/wiki/Apostle_(film)",
  "poster": "",
  "rates": {
   "dima": 5,
   "deni": 5,
   "yura": 6,
   "ihor": 4
  }
 },
 {
  "id": 30,
  "title": "Фантазм",
  "titleEn": "Phantasm",
  "year": 1979,
  "country": "США",
  "director": "Дон Коскареллі",
  "genre": "Жахи, Фантастика",
  "season": "2020",
  "date": "2020-06-13",
  "imdb": "https://www.imdb.com/title/tt0079840/",
  "wiki": "https://en.wikipedia.org/wiki/Phantasm_(film)",
  "poster": "",
  "rates": {
   "dima": 4,
   "deni": 4,
   "yura": 5,
   "ihor": 3
  }
 },
 {
  "id": 29,
  "title": "Зоряний десант",
  "titleEn": "Starship Troopers",
  "year": 1997,
  "country": "США",
  "director": "Пол Верховен",
  "genre": "Фантастика, Бойовик",
  "season": "2020",
  "date": "2020-06-13",
  "imdb": "https://www.imdb.com/title/tt0120184/",
  "wiki": "https://en.wikipedia.org/wiki/Starship_Troopers",
  "poster": "",
  "rates": {
   "dima": 8,
   "deni": 8,
   "yura": 10,
   "ihor": 8
  }
 },
 {
  "id": 28,
  "title": "Книга Мертвих",
  "titleEn": "Necronomicon",
  "year": 1993,
  "country": "США",
  "director": "Крістоф Ганс та ін.",
  "genre": "Жахи",
  "season": "2020",
  "date": "2020-03-01",
  "imdb": "https://www.imdb.com/title/tt0107666/",
  "wiki": "https://en.wikipedia.org/wiki/Necronomicon_(film)",
  "poster": "",
  "rates": {
   "dima": 6,
   "deni": 5,
   "yura": 7,
   "ihor": 4
  }
 },
 {
  "id": 27,
  "title": "Прокляття",
  "titleEn": "The Grudge",
  "year": 2020,
  "country": "США",
  "director": "Ніколас Песке",
  "genre": "Жахи",
  "season": "2020",
  "date": "2020-03-01",
  "imdb": "https://www.imdb.com/title/tt3612126/",
  "wiki": "https://en.wikipedia.org/wiki/The_Grudge_(2020_film)",
  "poster": "",
  "rates": {
   "dima": 4,
   "deni": 5,
   "yura": 5,
   "ihor": 4
  }
 },
 {
  "id": 26,
  "title": "День звіра",
  "titleEn": "The Day of the Beast",
  "year": 1995,
  "country": "Іспанія",
  "director": "Алекс де ла Іглесія",
  "genre": "Жахи, Комедія",
  "season": "2020",
  "date": "2020-01-25",
  "imdb": "https://www.imdb.com/title/tt0113671/",
  "wiki": "https://en.wikipedia.org/wiki/The_Day_of_the_Beast",
  "poster": "",
  "rates": {
   "dima": 4,
   "deni": 4,
   "yura": 5,
   "ihor": 4
  }
 },
 {
  "id": 25,
  "title": "П'ятниця, 13-те (1980)",
  "titleEn": "Friday the 13th",
  "year": 1980,
  "country": "США",
  "director": "Шон С. Каннінгем",
  "genre": "Жахи, Слешер",
  "season": "2020",
  "date": "2020-01-18",
  "imdb": "https://www.imdb.com/title/tt0080761/",
  "wiki": "https://en.wikipedia.org/wiki/Friday_the_13th_(1980_film)",
  "poster": "",
  "rates": {
   "dima": 6,
   "deni": 6,
   "yura": 7,
   "ihor": 0
  }
 },
 {
  "id": 24,
  "title": "Демон всередині",
  "titleEn": "The Autopsy of Jane Doe",
  "year": 2016,
  "country": "США, Велика Британія",
  "director": "Андре Ередал",
  "genre": "Жахи",
  "season": "2019",
  "date": "2019-12-28",
  "imdb": "https://www.imdb.com/title/tt3289956/",
  "wiki": "https://en.wikipedia.org/wiki/The_Autopsy_of_Jane_Doe",
  "poster": "",
  "rates": {
   "dima": 6,
   "deni": 7,
   "yura": 7,
   "ihor": 8
  }
 },
 {
  "id": 23,
  "title": "Сіністер",
  "titleEn": "Sinister",
  "year": 2012,
  "country": "США",
  "director": "Скотт Дерріксон",
  "genre": "Жахи",
  "season": "2019",
  "date": "2019-12-28",
  "imdb": "https://www.imdb.com/title/tt1922777/",
  "wiki": "https://en.wikipedia.org/wiki/Sinister_(film)",
  "poster": "",
  "rates": {
   "dima": 7,
   "deni": 7,
   "yura": 6,
   "ihor": 7
  }
 },
 {
  "id": 22,
  "title": "Телефон диявола",
  "titleEn": "976-EVIL",
  "year": 1988,
  "country": "США",
  "director": "Роберт Інглунд",
  "genre": "Жахи",
  "season": "2019",
  "date": "2019-12-28",
  "imdb": "https://www.imdb.com/title/tt0095689/",
  "wiki": "https://en.wikipedia.org/wiki/976-EVIL",
  "poster": "",
  "rates": {
   "dima": 3,
   "deni": 5,
   "yura": 3,
   "ihor": 4
  }
 },
 {
  "id": 21,
  "title": "Відеодром",
  "titleEn": "Videodrome",
  "year": 1983,
  "country": "Канада",
  "director": "Девід Кроненберг",
  "genre": "Жахи, Фантастика",
  "season": "2019",
  "date": "2019-12-14",
  "imdb": "https://www.imdb.com/title/tt0086541/",
  "wiki": "https://en.wikipedia.org/wiki/Videodrome",
  "poster": "",
  "rates": {
   "dima": 6,
   "deni": 5,
   "yura": 6,
   "ihor": 3
  }
 },
 {
  "id": 20,
  "title": "Лепрекон 2",
  "titleEn": "Leprechaun 2",
  "year": 1994,
  "country": "США",
  "director": "Родман Флендер",
  "genre": "Жахи, Комедія",
  "season": "2019",
  "date": "2019-12-14",
  "imdb": "https://www.imdb.com/title/tt0110591/",
  "wiki": "https://en.wikipedia.org/wiki/Leprechaun_2",
  "poster": "",
  "rates": {
   "dima": 6,
   "deni": 6,
   "yura": 8,
   "ihor": 8
  }
 },
 {
  "id": 19,
  "title": "Офісний простір",
  "titleEn": "Office Space",
  "year": 1999,
  "country": "США",
  "director": "Майк Джадж",
  "genre": "Комедія",
  "season": "2019",
  "date": "2019-12-14",
  "imdb": "https://www.imdb.com/title/tt0151804/",
  "wiki": "https://en.wikipedia.org/wiki/Office_Space",
  "poster": "",
  "rates": {
   "dima": 7,
   "deni": 7,
   "yura": 5,
   "ihor": 0
  }
 },
 {
  "id": 18,
  "title": "Кошмар на вулиці В'язів",
  "titleEn": "A Nightmare on Elm Street",
  "year": 1984,
  "country": "США",
  "director": "Вес Крейвен",
  "genre": "Жахи, Слешер",
  "season": "2019",
  "date": "2019-12-14",
  "imdb": "https://www.imdb.com/title/tt0087800/",
  "wiki": "https://en.wikipedia.org/wiki/A_Nightmare_on_Elm_Street_(1984_film)",
  "poster": "",
  "rates": {
   "dima": 7,
   "deni": 7,
   "yura": 8,
   "ihor": 5
  }
 },
 {
  "id": 17,
  "title": "Повернення живих мерців",
  "titleEn": "The Return of the Living Dead",
  "year": 1985,
  "country": "США",
  "director": "Ден О'Беннон",
  "genre": "Жахи, Комедія",
  "season": "2019",
  "date": "2019-11-23",
  "imdb": "https://www.imdb.com/title/tt0089907/",
  "wiki": "https://en.wikipedia.org/wiki/The_Return_of_the_Living_Dead",
  "poster": "",
  "rates": {
   "dima": 5,
   "deni": 7,
   "yura": 7,
   "ihor": 8
  }
 },
 {
  "id": 16,
  "title": "Закоханий могильник",
  "titleEn": "Dellamorte Dellamore",
  "year": 1994,
  "country": "Італія",
  "director": "Мікеле Соаві",
  "genre": "Жахи, Комедія",
  "season": "2019",
  "date": "2019-10-05",
  "imdb": "https://www.imdb.com/title/tt0109575/",
  "wiki": "https://en.wikipedia.org/wiki/Dellamorte_Dellamore",
  "poster": "",
  "rates": {
   "dima": 8,
   "deni": 10,
   "yura": 10,
   "ihor": 10
  }
 },
 {
  "id": 15,
  "title": "Драбина Джейкоба",
  "titleEn": "Jacob's Ladder",
  "year": 1990,
  "country": "США",
  "director": "Едріан Лайн",
  "genre": "Жахи, Трилер",
  "season": "2019",
  "date": "2019-10-05",
  "imdb": "https://www.imdb.com/title/tt0099674/",
  "wiki": "https://en.wikipedia.org/wiki/Jacob's_Ladder_(1990_film)",
  "poster": "",
  "rates": {
   "dima": 6,
   "deni": 7,
   "yura": 6,
   "ihor": 7
  }
 },
 {
  "id": 14,
  "title": "Ззовні",
  "titleEn": "Get Out",
  "year": 2017,
  "country": "США",
  "director": "Джордан Піл",
  "genre": "Жахи, Трилер",
  "season": "2019",
  "date": "2019-10-05",
  "imdb": "https://www.imdb.com/title/tt5052448/",
  "wiki": "https://en.wikipedia.org/wiki/Get_Out",
  "poster": "",
  "rates": {
   "dima": 4,
   "deni": 5,
   "yura": 6,
   "ihor": 2
  }
 },
 {
  "id": 13,
  "title": "Реаніматор",
  "titleEn": "Re-Animator",
  "year": 1985,
  "country": "США",
  "director": "Стюарт Ґордон",
  "genre": "Жахи, Фантастика",
  "season": "2019",
  "date": "2019-09-29",
  "imdb": "https://www.imdb.com/title/tt0089871/",
  "wiki": "https://en.wikipedia.org/wiki/Re-Animator",
  "poster": "",
  "rates": {
   "dima": 7,
   "deni": 7,
   "yura": 7,
   "ihor": 6
  }
 },
 {
  "id": 12,
  "title": "Дагон",
  "titleEn": "Dagon",
  "year": 2001,
  "country": "Іспанія",
  "director": "Стюарт Ґордон",
  "genre": "Жахи",
  "season": "2019",
  "date": "2019-09-28",
  "imdb": "https://www.imdb.com/title/tt0134508/",
  "wiki": "https://en.wikipedia.org/wiki/Dagon_(film)",
  "poster": "",
  "rates": {
   "dima": 7,
   "deni": 6,
   "yura": 6,
   "ihor": 5
  }
 },
 {
  "id": 11,
  "title": "Лепрекон 4: У космосі",
  "titleEn": "Leprechaun 4: In Space",
  "year": 1997,
  "country": "США",
  "director": "Браян Тренчард-Сміт",
  "genre": "Жахи, Комедія",
  "season": "2019",
  "date": "2019-09-28",
  "imdb": "https://www.imdb.com/title/tt0118596/",
  "wiki": "https://en.wikipedia.org/wiki/Leprechaun_4:_In_Space",
  "poster": "",
  "rates": {
   "dima": 0,
   "deni": 4,
   "yura": 10,
   "ihor": 0
  }
 },
 {
  "id": 10,
  "title": "Троль 2",
  "titleEn": "Troll 2",
  "year": 1990,
  "country": "Італія",
  "director": "Клаудіо Фраґассо",
  "genre": "Жахи",
  "season": "2019",
  "date": "2019-09-28",
  "imdb": "https://www.imdb.com/title/tt0100849/",
  "wiki": "https://en.wikipedia.org/wiki/Troll_2",
  "poster": "",
  "rates": {
   "dima": 3,
   "deni": 2,
   "yura": 4,
   "ihor": 8
  }
 },
 {
  "id": 9,
  "title": "Великий переполох у малому Китаї",
  "titleEn": "Big Trouble in Little China",
  "year": 1986,
  "country": "США",
  "director": "Джон Карпентер",
  "genre": "Бойовик, Фентезі",
  "season": "2019",
  "date": "2019-08-28",
  "imdb": "https://www.imdb.com/title/tt0090728/",
  "wiki": "https://en.wikipedia.org/wiki/Big_Trouble_in_Little_China",
  "poster": "",
  "rates": {
   "dima": 7,
   "deni": 7,
   "yura": 7,
   "ihor": 0
  }
 },
 {
  "id": 8,
  "title": "Ніч кошмарів",
  "titleEn": "Night of the Creeps",
  "year": 1986,
  "country": "США",
  "director": "Фред Деккер",
  "genre": "Жахи, Комедія",
  "season": "2019",
  "date": "2019-08-28",
  "imdb": "https://www.imdb.com/title/tt0091636/",
  "wiki": "https://en.wikipedia.org/wiki/Night_of_the_Creeps",
  "poster": "",
  "rates": {
   "dima": 3,
   "deni": 5,
   "yura": 6,
   "ihor": 0
  }
 },
 {
  "id": 7,
  "title": "Муха",
  "titleEn": "The Fly",
  "year": 1986,
  "country": "США, Велика Британія, Канада",
  "director": "Девід Кроненберг",
  "genre": "Жахи, Фантастика",
  "season": "2019",
  "date": "2019-08-28",
  "imdb": "https://www.imdb.com/title/tt0091064/",
  "wiki": "https://en.wikipedia.org/wiki/The_Fly_(1986_film)",
  "poster": "",
  "rates": {
   "dima": 7,
   "deni": 6,
   "yura": 5,
   "ihor": 0
  }
 },
 {
  "id": 6,
  "title": "Принц темряви",
  "titleEn": "Prince of Darkness",
  "year": 1987,
  "country": "США",
  "director": "Джон Карпентер",
  "genre": "Жахи",
  "season": "2019",
  "date": "2019-08-28",
  "imdb": "https://www.imdb.com/title/tt0093760/",
  "wiki": "https://en.wikipedia.org/wiki/Prince_of_Darkness_(film)",
  "poster": "",
  "rates": {
   "dima": 3,
   "deni": 3,
   "yura": 5,
   "ihor": 0
  }
 },
 {
  "id": 5,
  "title": "Мішки для трупів",
  "titleEn": "Basket Case",
  "year": 1982,
  "country": "США",
  "director": "Френк Хененлоттер",
  "genre": "Жахи",
  "season": "2019",
  "date": "2019-08-28",
  "imdb": "https://www.imdb.com/title/tt0083624/",
  "wiki": "https://en.wikipedia.org/wiki/Basket_Case_(film)",
  "poster": "",
  "rates": {
   "dima": 7,
   "deni": 7,
   "yura": 7,
   "ihor": 0
  }
 },
 {
  "id": 4,
  "title": "Лепрекон 3",
  "titleEn": "Leprechaun 3",
  "year": 1995,
  "country": "США",
  "director": "Браян Тренчард-Сміт",
  "genre": "Жахи, Комедія",
  "season": "2019",
  "date": "2019-08-28",
  "imdb": "https://www.imdb.com/title/tt0113189/",
  "wiki": "https://en.wikipedia.org/wiki/Leprechaun_3",
  "poster": "",
  "rates": {
   "dima": 4,
   "deni": 5,
   "yura": 6,
   "ihor": 0
  }
 },
 {
  "id": 3,
  "title": "У пащі божевілля",
  "titleEn": "In the Mouth of Madness",
  "year": 1994,
  "country": "США",
  "director": "Джон Карпентер",
  "genre": "Жахи",
  "season": "2019",
  "date": "2019-08-28",
  "imdb": "https://www.imdb.com/title/tt0113409/",
  "wiki": "https://en.wikipedia.org/wiki/In_the_Mouth_of_Madness",
  "poster": "",
  "rates": {
   "dima": 7,
   "deni": 5,
   "yura": 3,
   "ihor": 0
  }
 }
];

export const RATERS = [
  { key: "dima", name: "Dima",  color: "#4cc9f0" },
  { key: "deni", name: "Deni",  color: "#f72585" },
  { key: "yura", name: "Yura",  color: "#90be6d" },
  { key: "ihor", name: "Ihor",  color: "#f9a620" },
];

export function avgRate(rates) {
  if (!rates) return 0;
  const vals = Object.values(rates).filter(v => v > 0);
  if (!vals.length) return 0;
  return vals.reduce((a, b) => a + b, 0) / vals.length;
}

export function seasonFromDate(dateStr) {
  return (dateStr || "").slice(0, 4);
}

export function decadeOf(year) {
  year = Number(year);
  if (!year) return null;
  return Math.floor(year / 10) * 10;
}

// ============================================================
// Country name normalization
// Wikipedia/Wikidata returns full official names ("Сполучені Штати
// Америки") while the club database uses short names ("США").
// Every country string is canonicalized so filtering, statistics and
// the table show ONE value per country, never two spellings.
// ============================================================
const COUNTRY_ALIASES = {
  // USA
  "сполучені штати америки": "США",
  "сполучені штати": "США",
  "usa": "США", "us": "США",
  "united states": "США", "united states of america": "США",
  // United Kingdom
  "об'єднане королівство великої британії та північної ірландії": "Велика Британія",
  "об'єднане королівство великої британії і північної ірландії": "Велика Британія",
  "об'єднане королівство": "Велика Британія",
  "сполучене королівство": "Велика Британія",
  "united kingdom": "Велика Британія", "great britain": "Велика Британія",
  // USSR
  "союз радянських соціалістичних республік": "СРСР",
  "радянський союз": "СРСР",
  "ussr": "СРСР", "soviet union": "СРСР",
  // Russia
  "російська федерація": "Росія",
  "russian federation": "Росія",
  // Koreas
  ["республіка коре" + "я"]: "Південна Корея",
  "south korea": "Південна Корея",
  "корейська народно-демократична республіка": "Північна Корея",
  "north korea": "Північна Корея",
  // China
  "китайська народна республіка": "Китай",
  "china": "Китай",
  // Germany
  "федеративна республіка німеччина": "Німеччина",
  "німецька демократична республіка": "НДР",
  // Others
  "чехо-словаччина": "Чехословаччина",
  "чехословацька соціалістична республіка": "Чехословаччина",
  "чеська республіка": "Чехія",
  "об'єднані арабські емірати": "ОАЕ",
  "французька республіка": "Франція",
  "ісламська республіка іран": "Іран",
  "нова зеландія aotearoa": "Нова Зеландія",
};

export function normalizeOneCountry(name) {
  let s = String(name || "").trim().replace(/\s+/g, " ");
  if (!s) return "";
  // drop trailing punctuation and parenthetical clarifications:
  // "США." → "США", "Німеччина (ФРН)" → "Німеччина"
  s = s.replace(/[.․,;:]+$/, "").replace(/\s*\([^)]*\)\s*$/, "").trim();
  const key = s.toLowerCase();
  return COUNTRY_ALIASES[key] || s;
}

// "США, Сполучені Штати Америки" → "США"; also fixes multi-country strings
export function normalizeCountry(country) {
  const raw = String(country || "").trim();
  if (!raw) return "";
  // the whole string may itself be one full official name
  // ("Об'єднане Королівство … та Північної Ірландії" — contains " та ")
  const whole = normalizeOneCountry(raw);
  if (whole && whole !== raw) return whole;
  const parts = raw.split(/[,;/]| і | та /).map(normalizeOneCountry).filter(Boolean);
  return [...new Set(parts)].join(", ");
}
